apiVersion: v1
kind: Service
metadata:
  name: hspmgmt-service
  namespace: hospital
spec:
  selector:
    app: hspmgmt  # this must match the labels in your deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
