# hspmgmt-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hspmgmt-service
  namespace: hospital
spec:
  selector:
    app: hspmgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
